name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  build-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: leosfs/teste-ci-cd:latest

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Build Docker image
      #   id: build
      #   run: |
      #     IMAGE_TAG=$(date -u +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)
      #     docker build \
      #       --platform linux/amd64 \
      #       --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
      #       --build-arg VCS_REF=$(git rev-parse --short HEAD) \
      #       --tag leosfs/teste-ci-cd:${IMAGE_TAG} \
      #       --tag leosfs/teste-ci-cd:latest \
      #       .
      #     echo "::set-output name=IMAGE_TAG::${IMAGE_TAG}"
      

  deploy-test:

    needs: build-ci
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    
    steps:
 

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: thetips4you/testjodejsapp
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  

  deploy-production:
    needs: build-ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: latest

      - run: docker build -t setup-nodejs .
      - run: echo "Deploy"